package maturita.rowsGen;

import java.io.IOException;
import java.util.ArrayList;

public class RowsGenApp {
    public static void main(String[] args) throws IOException {
        ArrayList<City> cities = new ArrayList<City>();

        cities.add(new City("Abha", 18.0));
        cities.add(new City("Abidjan", 26.0));
        cities.add(new City("Abéché", 29.4));
        cities.add(new City("Accra", 26.4));
        cities.add(new City("Addis Ababa", 16.0));
        cities.add(new City("Adelaide", 17.3));
        cities.add(new City("Aden", 29.1));
        cities.add(new City("Ahvaz", 25.4));
        cities.add(new City("Albuquerque", 14.0));
        cities.add(new City("Alexandra", 11.0));
        cities.add(new City("Alexandria", 20.0));
        cities.add(new City("Algiers", 18.2));
        cities.add(new City("Alice Springs", 21.0));
        cities.add(new City("Almaty", 10.0));
        cities.add(new City("Amsterdam", 10.2));
        cities.add(new City("Anadyr", -6.9));
        cities.add(new City("Anchorage", 2.8));
        cities.add(new City("Andorra la Vella", 9.8));
        cities.add(new City("Ankara", 12.0));
        cities.add(new City("Antananarivo", 17.9));
        cities.add(new City("Antsiranana", 25.2));
        cities.add(new City("Arkhangelsk", 1.3));
        cities.add(new City("Ashgabat", 17.1));
        cities.add(new City("Asmara", 15.6));
        cities.add(new City("Assab", 30.5));
        cities.add(new City("Astana", 3.5));
        cities.add(new City("Athens", 19.2));
        cities.add(new City("Atlanta", 17.0));
        cities.add(new City("Auckland", 15.2));
        cities.add(new City("Austin", 20.7));
        cities.add(new City("Baghdad", 22.77));
        cities.add(new City("Baguio", 19.5));
        cities.add(new City("Baku", 15.1));
        cities.add(new City("Baltimore", 13.1));
        cities.add(new City("Bamako", 27.8));
        cities.add(new City("Bangkok", 28.6));
        cities.add(new City("Bangui", 26.0));
        cities.add(new City("Banjul", 26.0));
        cities.add(new City("Barcelona", 18.2));
        cities.add(new City("Bata", 25.1));
        cities.add(new City("Batumi", 14.0));
        cities.add(new City("Beijing", 12.9));
        cities.add(new City("Beirut", 20.9));
        cities.add(new City("Belgrade", 12.5));
        cities.add(new City("Belize City", 26.7));
        cities.add(new City("Benghazi", 19.9));
        cities.add(new City("Bergen", 7.7));
        cities.add(new City("Berlin", 10.3));
        cities.add(new City("Bilbao", 14.7));
        cities.add(new City("Birao", 26.5));
        cities.add(new City("Bishkek", 11.3));
        cities.add(new City("Bissau", 27.0));
        cities.add(new City("Blantyre", 22.2));
        cities.add(new City("Bloemfontein", 15.6));
        cities.add(new City("Boise", 11.4));
        cities.add(new City("Bordeaux", 14.2));
        cities.add(new City("Bosaso", 30.0));
        cities.add(new City("Boston", 10.9));
        cities.add(new City("Bouaké", 26.0));
        cities.add(new City("Bratislava", 10.5));
        cities.add(new City("Brazzaville", 25.0));
        cities.add(new City("Bridgetown", 27.0));
        cities.add(new City("Brisbane", 21.4));
        cities.add(new City("Brussels", 10.5));
        cities.add(new City("Bucharest", 10.8));
        cities.add(new City("Budapest", 11.3));
        cities.add(new City("Bujumbura", 23.8));
        cities.add(new City("Bulawayo", 18.9));
        cities.add(new City("Burnie", 13.1));
        cities.add(new City("Busan", 15.0));
        cities.add(new City("Cabo San Lucas", 23.9));
        cities.add(new City("Cairns", 25.0));
        cities.add(new City("Cairo", 21.4));
        cities.add(new City("Calgary", 4.4));
        cities.add(new City("Canberra", 13.1));
        cities.add(new City("Cape Town", 16.2));
        cities.add(new City("Changsha", 17.4));
        cities.add(new City("Charlotte", 16.1));
        cities.add(new City("Chiang Mai", 25.8));
        cities.add(new City("Chicago", 9.8));
        cities.add(new City("Chihuahua", 18.6));
        cities.add(new City("Chișinău", 10.2));
        cities.add(new City("Chittagong", 25.9));
        cities.add(new City("Chongqing", 18.6));
        cities.add(new City("Christchurch", 12.2));
        cities.add(new City("City of San Marino", 11.8));
        cities.add(new City("Colombo", 27.4));
        cities.add(new City("Columbus", 11.7));
        cities.add(new City("Conakry", 26.4));
        cities.add(new City("Copenhagen", 9.1));
        cities.add(new City("Cotonou", 27.2));
        cities.add(new City("Cracow", 9.3));
        cities.add(new City("Da Lat", 17.9));
        cities.add(new City("Da Nang", 25.8));
        cities.add(new City("Dakar", 24.0));
        cities.add(new City("Dallas", 19.0));
        cities.add(new City("Damascus", 17.0));
        cities.add(new City("Dampier", 26.4));
        cities.add(new City("Dar es Salaam", 25.8));
        cities.add(new City("Darwin", 27.6));
        cities.add(new City("Denpasar", 23.7));
        cities.add(new City("Denver", 10.4));
        cities.add(new City("Detroit", 10.0));
        cities.add(new City("Dhaka", 25.9));
        cities.add(new City("Dikson", -11.1));
        cities.add(new City("Dili", 26.6));
        cities.add(new City("Djibouti", 29.9));
        cities.add(new City("Dodoma", 22.7));
        cities.add(new City("Dolisie", 24.0));
        cities.add(new City("Douala", 26.7));
        cities.add(new City("Dubai", 26.9));
        cities.add(new City("Dublin", 9.8));
        cities.add(new City("Dunedin", 11.1));
        cities.add(new City("Durban", 20.6));
        cities.add(new City("Dushanbe", 14.7));
        cities.add(new City("Edinburgh", 9.3));
        cities.add(new City("Edmonton", 4.2));
        cities.add(new City("El Paso", 18.1));
        cities.add(new City("Entebbe", 21.0));
        cities.add(new City("Erbil", 19.5));
        cities.add(new City("Erzurum", 5.1));
        cities.add(new City("Fairbanks", -2.3));
        cities.add(new City("Fianarantsoa", 17.9));
        cities.add(new City("Flores,  Petén", 26.4));
        cities.add(new City("Frankfurt", 10.6));
        cities.add(new City("Fresno", 17.9));
        cities.add(new City("Fukuoka", 17.0));
        cities.add(new City("Gabès", 19.5));
        cities.add(new City("Gaborone", 21.0));
        cities.add(new City("Gagnoa", 26.0));
        cities.add(new City("Gangtok", 15.2));
        cities.add(new City("Garissa", 29.3));
        cities.add(new City("Garoua", 28.3));
        cities.add(new City("George Town", 27.9));
        cities.add(new City("Ghanzi", 21.4));
        cities.add(new City("Gjoa Haven", -14.4));
        cities.add(new City("Guadalajara", 20.9));
        cities.add(new City("Guangzhou", 22.4));
        cities.add(new City("Guatemala City", 20.4));
        cities.add(new City("Halifax", 7.5));
        cities.add(new City("Hamburg", 9.7));
        cities.add(new City("Hamilton", 13.8));
        cities.add(new City("Hanga Roa", 20.5));
        cities.add(new City("Hanoi", 23.6));
        cities.add(new City("Harare", 18.4));
        cities.add(new City("Harbin", 5.0));
        cities.add(new City("Hargeisa", 21.7));
        cities.add(new City("Hat Yai", 27.0));
        cities.add(new City("Havana", 25.2));
        cities.add(new City("Helsinki", 5.9));
        cities.add(new City("Heraklion", 18.9));
        cities.add(new City("Hiroshima", 16.3));
        cities.add(new City("Ho Chi Minh City", 27.4));
        cities.add(new City("Hobart", 12.7));
        cities.add(new City("Hong Kong", 23.3));
        cities.add(new City("Honiara", 26.5));
        cities.add(new City("Honolulu", 25.4));
        cities.add(new City("Houston", 20.8));
        cities.add(new City("Ifrane", 11.4));
        cities.add(new City("Indianapolis", 11.8));
        cities.add(new City("Iqaluit", -9.3));
        cities.add(new City("Irkutsk", 1.0));
        cities.add(new City("Istanbul", 13.9));
        cities.add(new City("İzmir", 17.9));
        cities.add(new City("Jacksonville", 20.3));
        cities.add(new City("Jakarta", 26.7));
        cities.add(new City("Jayapura", 27.0));
        cities.add(new City("Jerusalem", 18.3));
        cities.add(new City("Johannesburg", 15.5));
        cities.add(new City("Jos", 22.8));
        cities.add(new City("Juba", 27.8));
        cities.add(new City("Kabul", 12.1));
        cities.add(new City("Kampala", 20.0));
        cities.add(new City("Kandi", 27.7));
        cities.add(new City("Kankan", 26.5));
        cities.add(new City("Kano", 26.4));
        cities.add(new City("Kansas City", 12.5));
        cities.add(new City("Karachi", 26.0));
        cities.add(new City("Karonga", 24.4));
        cities.add(new City("Kathmandu", 18.3));
        cities.add(new City("Khartoum", 29.9));
        cities.add(new City("Kingston", 27.4));
        cities.add(new City("Kinshasa", 25.3));
        cities.add(new City("Kolkata", 26.7));
        cities.add(new City("Kuala Lumpur", 27.3));
        cities.add(new City("Kumasi", 26.0));
        cities.add(new City("Kunming", 15.7));
        cities.add(new City("Kuopio", 3.4));
        cities.add(new City("Kuwait City", 25.7));
        cities.add(new City("Kyiv", 8.4));
        cities.add(new City("Kyoto", 15.8));
        cities.add(new City("La Ceiba", 26.2));
        cities.add(new City("La Paz", 23.7));
        cities.add(new City("Lagos", 26.8));
        cities.add(new City("Lahore", 24.3));
        cities.add(new City("Lake Havasu City", 23.7));
        cities.add(new City("Lake Tekapo", 8.7));
        cities.add(new City("Las Palmas de Gran Canaria", 21.2));
        cities.add(new City("Las Vegas", 20.3));
        cities.add(new City("Launceston", 13.1));
        cities.add(new City("Lhasa", 7.6));
        cities.add(new City("Libreville", 25.9));
        cities.add(new City("Lisbon", 17.5));
        cities.add(new City("Livingstone", 21.8));
        cities.add(new City("Ljubljana", 10.9));
        cities.add(new City("Lodwar", 29.3));
        cities.add(new City("Lomé", 26.9));
        cities.add(new City("London", 11.3));
        cities.add(new City("Los Angeles", 18.6));
        cities.add(new City("Louisville", 13.9));
        cities.add(new City("Luanda", 25.8));
        cities.add(new City("Lubumbashi", 20.8));
        cities.add(new City("Lusaka", 19.9));
        cities.add(new City("Luxembourg City", 9.3));
        cities.add(new City("Lviv", 7.8));
        cities.add(new City("Lyon", 12.5));
        cities.add(new City("Madrid", 15.0));
        cities.add(new City("Mahajanga", 26.3));
        cities.add(new City("Makassar", 26.7));
        cities.add(new City("Makurdi", 26.0));
        cities.add(new City("Malabo", 26.3));
        cities.add(new City("Malé", 28.0));
        cities.add(new City("Managua", 27.3));
        cities.add(new City("Manama", 26.5));
        cities.add(new City("Mandalay", 28.0));
        cities.add(new City("Mango", 28.1));
        cities.add(new City("Manila", 28.4));
        cities.add(new City("Maputo", 22.8));
        cities.add(new City("Marrakesh", 19.6));
        cities.add(new City("Marseille", 15.8));
        cities.add(new City("Maun", 22.4));
        cities.add(new City("Medan", 26.5));
        cities.add(new City("Mek'ele", 22.7));
        cities.add(new City("Melbourne", 15.1));
        cities.add(new City("Memphis", 17.2));
        cities.add(new City("Mexicali", 23.1));
        cities.add(new City("Mexico City", 17.5));
        cities.add(new City("Miami", 24.9));
        cities.add(new City("Milan", 13.0));
        cities.add(new City("Milwaukee", 8.9));
        cities.add(new City("Minneapolis", 7.8));
        cities.add(new City("Minsk", 6.7));
        cities.add(new City("Mogadishu", 27.1));
        cities.add(new City("Mombasa", 26.3));
        cities.add(new City("Monaco", 16.4));
        cities.add(new City("Moncton", 6.1));
        cities.add(new City("Monterrey", 22.3));
        cities.add(new City("Montreal", 6.8));
        cities.add(new City("Moscow", 5.8));
        cities.add(new City("Mumbai", 27.1));
        cities.add(new City("Murmansk", 0.6));
        cities.add(new City("Muscat", 28.0));
        cities.add(new City("Mzuzu", 17.7));
        cities.add(new City("N'Djamena", 28.3));
        cities.add(new City("Naha", 23.1));
        cities.add(new City("Nairobi", 17.8));
        cities.add(new City("Nakhon Ratchasima", 27.3));
        cities.add(new City("Napier", 14.6));
        cities.add(new City("Napoli", 15.9));
        cities.add(new City("Nashville", 15.4));
        cities.add(new City("Nassau", 24.6));
        cities.add(new City("Ndola", 20.3));
        cities.add(new City("New Delhi", 25.0));
        cities.add(new City("New Orleans", 20.7));
        cities.add(new City("New York City", 12.9));
        cities.add(new City("Ngaoundéré", 22.0));
        cities.add(new City("Niamey", 29.3));
        cities.add(new City("Nicosia", 19.7));
        cities.add(new City("Niigata", 13.9));
        cities.add(new City("Nouadhibou", 21.3));
        cities.add(new City("Nouakchott", 25.7));
        cities.add(new City("Novosibirsk", 1.7));
        cities.add(new City("Nuuk", -1.4));
        cities.add(new City("Odesa", 10.7));
        cities.add(new City("Odienné", 26.0));
        cities.add(new City("Oklahoma City", 15.9));
        cities.add(new City("Omaha", 10.6));
        cities.add(new City("Oranjestad", 28.1));
        cities.add(new City("Oslo", 5.7));
        cities.add(new City("Ottawa", 6.6));
        cities.add(new City("Ouagadougou", 28.3));
        cities.add(new City("Ouahigouya", 28.6));
        cities.add(new City("Ouarzazate", 18.9));
        cities.add(new City("Oulu", 2.7));
        cities.add(new City("Palembang", 27.3));
        cities.add(new City("Palermo", 18.5));
        cities.add(new City("Palm Springs", 24.5));
        cities.add(new City("Palmerston North", 13.2));
        cities.add(new City("Panama City", 28.0));
        cities.add(new City("Parakou", 26.8));
        cities.add(new City("Paris", 12.3));
        cities.add(new City("Perth", 18.7));
        cities.add(new City("Petropavlovsk-Kamchatsky", 1.9));
        cities.add(new City("Philadelphia", 13.2));
        cities.add(new City("Phnom Penh", 28.3));
        cities.add(new City("Phoenix", 23.9));
        cities.add(new City("Pittsburgh", 10.8));
        cities.add(new City("Podgorica", 15.3));
        cities.add(new City("Pointe-Noire", 26.1));
        cities.add(new City("Pontianak", 27.7));
        cities.add(new City("Port Moresby", 26.9));
        cities.add(new City("Port Sudan", 28.4));
        cities.add(new City("Port Vila", 24.3));
        cities.add(new City("Port-Gentil", 26.0));
        cities.add(new City("Portland (new City(OR))", 12.4));
        cities.add(new City("Porto", 15.7));
        cities.add(new City("Prague", 8.4));
        cities.add(new City("Praia", 24.4));
        cities.add(new City("Pretoria", 18.2));
        cities.add(new City("Pyongyang", 10.8));
        cities.add(new City("Rabat", 17.2));
        cities.add(new City("Rangpur", 24.4));
        cities.add(new City("Reggane", 28.3));
        cities.add(new City("Reykjavík", 4.3));
        cities.add(new City("Riga", 6.2));
        cities.add(new City("Riyadh", 26.0));
        cities.add(new City("Rome", 15.2));
        cities.add(new City("Roseau", 26.2));
        cities.add(new City("Rostov-on-Don", 9.9));
        cities.add(new City("Sacramento", 16.3));
        cities.add(new City("Saint Petersburg", 5.8));
        cities.add(new City("Saint-Pierre", 5.7));
        cities.add(new City("Salt Lake City", 11.6));
        cities.add(new City("San Antonio", 20.8));
        cities.add(new City("San Diego", 17.8));
        cities.add(new City("San Francisco", 14.6));
        cities.add(new City("San Jose", 16.4));
        cities.add(new City("San José", 22.6));
        cities.add(new City("San Juan", 27.2));
        cities.add(new City("San Salvador", 23.1));
        cities.add(new City("Sana'a", 20.0));
        cities.add(new City("Santo Domingo", 25.9));
        cities.add(new City("Sapporo", 8.9));
        cities.add(new City("Sarajevo", 10.1));
        cities.add(new City("Saskatoon", 3.3));
        cities.add(new City("Seattle", 11.3));
        cities.add(new City("Ségou", 28.0));
        cities.add(new City("Seoul", 12.5));
        cities.add(new City("Seville", 19.2));
        cities.add(new City("Shanghai", 16.7));
        cities.add(new City("Singapore", 27.0));
        cities.add(new City("Skopje", 12.4));
        cities.add(new City("Sochi", 14.2));
        cities.add(new City("Sofia", 10.6));
        cities.add(new City("Sokoto", 28.0));
        cities.add(new City("Split", 16.1));
        cities.add(new City("St. John's", 5.0));
        cities.add(new City("St. Louis", 13.9));
        cities.add(new City("Stockholm", 6.6));
        cities.add(new City("Surabaya", 27.1));
        cities.add(new City("Suva", 25.6));
        cities.add(new City("Suwałki", 7.2));
        cities.add(new City("Sydney", 17.7));
        cities.add(new City("Tabora", 23.0));
        cities.add(new City("Tabriz", 12.6));
        cities.add(new City("Taipei", 23.0));
        cities.add(new City("Tallinn", 6.4));
        cities.add(new City("Tamale", 27.9));
        cities.add(new City("Tamanrasset", 21.7));
        cities.add(new City("Tampa", 22.9));
        cities.add(new City("Tashkent", 14.8));
        cities.add(new City("Tauranga", 14.8));
        cities.add(new City("Tbilisi", 12.9));
        cities.add(new City("Tegucigalpa", 21.7));
        cities.add(new City("Tehran", 17.0));
        cities.add(new City("Tel Aviv", 20.0));
        cities.add(new City("Thessaloniki", 16.0));
        cities.add(new City("Thiès", 24.0));
        cities.add(new City("Tijuana", 17.8));
        cities.add(new City("Timbuktu", 28.0));
        cities.add(new City("Tirana", 15.2));
        cities.add(new City("Toamasina", 23.4));
        cities.add(new City("Tokyo", 15.4));
        cities.add(new City("Toliara", 24.1));
        cities.add(new City("Toluca", 12.4));
        cities.add(new City("Toronto", 9.4));
        cities.add(new City("Tripoli", 20.0));
        cities.add(new City("Tromsø", 2.9));
        cities.add(new City("Tucson", 20.9));
        cities.add(new City("Tunis", 18.4));
        cities.add(new City("Ulaanbaatar", -0.4));
        cities.add(new City("Upington", 20.4));
        cities.add(new City("Ürümqi", 7.4));
        cities.add(new City("Vaduz", 10.1));
        cities.add(new City("Valencia", 18.3));
        cities.add(new City("Valletta", 18.8));
        cities.add(new City("Vancouver", 10.4));
        cities.add(new City("Veracruz", 25.4));
        cities.add(new City("Vienna", 10.4));
        cities.add(new City("Vientiane", 25.9));
        cities.add(new City("Villahermosa", 27.1));
        cities.add(new City("Vilnius", 6.0));
        cities.add(new City("Virginia Beach", 15.8));
        cities.add(new City("Vladivostok", 4.9));
        cities.add(new City("Warsaw", 8.5));
        cities.add(new City("Washington, D.C.", 14.6));
        cities.add(new City("Wau", 27.8));
        cities.add(new City("Wellington", 12.9));
        cities.add(new City("Whitehorse", -0.1));
        cities.add(new City("Wichita", 13.9));
        cities.add(new City("Willemstad", 28.0));
        cities.add(new City("Winnipeg", 3.0));
        cities.add(new City("Wrocław", 9.6));
        cities.add(new City("Xi'an", 14.1));
        cities.add(new City("Yakutsk", -8.8));
        cities.add(new City("Yangon", 27.5));
        cities.add(new City("Yaoundé", 23.8));
        cities.add(new City("Yellowknife", -4.3));
        cities.add(new City("Yerevan", 12.4));
        cities.add(new City("Yinchuan", 9.0));
        cities.add(new City("Zagreb", 10.7));
        cities.add(new City("Zanzibar City", 26.0));
        cities.add(new City("Zürich", 9.3));

        RowsGen demo = new RowsGen("maturita/rowsGen/text.txt", cities, 10000);
    }
}
